### ISSUE TITLE
unable to load configuration file after clean clone

### ISSUE THREAD

**Issue by francescofact** [GreyTeam2020/GoOutSafe_Primer2020#22]
If you clone the project it doesn't have the config/app.conf file for SendMail.py and the app throws an error. It should be included 

```
/usr/bin/python3.8 /home/francesco/Desktop/GoOutSafe_Primer2020/monolith/app.py
Traceback (most recent call last):
  File "/home/francesco/Desktop/GoOutSafe_Primer2020/monolith/app.py", line 3, in <module>
    from monolith.views import blueprints
  File "/home/francesco/Desktop/GoOutSafe_Primer2020/monolith/views/__init__.py", line 3, in <module>
    from .users import users
  File "/home/francesco/Desktop/GoOutSafe_Primer2020/monolith/views/users.py", line 4, in <module>
    from monolith.utils import SendMail
  File "/home/francesco/Desktop/GoOutSafe_Primer2020/monolith/utils/SendMail.py", line 8, in <module>
    app.config.from_pyfile(os.path.join("..", "config/app.conf"), silent=False)
  File "/home/francesco/.local/lib/python3.8/site-packages/flask/config.py", line 131, in from_pyfile
    with open(filename, mode="rb") as config_file:
FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/home/francesco/Desktop/GoOutSafe_Primer2020/monolith/utils/../config/app.conf'

Process finished with exit code 1
```

**Comment by vincenzopalazzo** [comment]
I can resolve this if you agree @francescofact, if yes can you assign this to me

**Comment by francescofact** [comment]
yes sure
