### ISSUE TITLE
Crash during the login

### ISSUE THREAD

**Issue by vincenzopalazzo** [GreyTeam2020/GoOutSafe_Primer2020#31]
After the user registration and the logout, I have the following exception

```
Traceback (most recent call last):
  File "/home/vincent/.local/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vincent/.local/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vincent/.local/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vincent/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vincent/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vincent/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vincent/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vincent/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vincent/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vincent/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vincent/GithubUnipi/GoOutSafe_Primer2020/monolith/views/auth.py", line 21, in login
    session['ROLE'] = role.value
AttributeError: 'NoneType' object has no attribute 'value'
127.0.0.1 - - [25/Oct/2020 19:37:46] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2020 19:37:46] "GET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2020 19:37:46] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2020 19:37:46] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2020 19:37:46] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

```

**Comment by reny77** [comment]
@vincenzopalazzo  I think that when you have registered the user, you haven't assign a role to it. Peraphs, we should put a mandatory constraint in foreign key role_id in user.

**Comment by vincenzopalazzo** [comment]
@reny77 thanks for this, I can manage it. We need only to decide how to set the role to the user when we have to register it, or maybe I'm missing somethings?
